services:
    wg-api-manager:
        image: wg
        container_name: wg-api-manager
        environment:
            - ADMIN_TOKEN=CHANGE_ME
        ports:
            - 3000:3000
            - 51820:51820/udp
        cap_add:
            - SYS_MODULE
            - NET_ADMIN
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
